apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: dataproduct-target-group
  namespace: nada
spec:
  image: {{ image }}
  schedule: '0 6 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 2
  concurrencyPolicy: Forbid
  gcp:
    bigQueryDatasets:
    - description: Metrikker på konsum av dataprodukter
      name: platform_users
      permission: READWRITE
